### ISSUE TITLE
Configurable resources

### ISSUE THREAD

**Issue by rapatel0** [ceph/cn#94] opened 2018-11-14 19:14 UTC
I'm trying to build a dev environment to reproduce an issue we are seeing in production. The issue is that ceph nano tops out at 512MB of RAM. An OOM error just hoses the container.

**Comment by leseb** [comment] 2018-11-20 12:34
Are you saying the container dies because the memory goes above 512MB?

**Comment by ErwanAliasr1** [comment] 2018-11-26 15:00
Can you describe how you went into this case ? How old was your container, what operation did you took, is it reproducible ? What version of ceph/ceph-container ?
thx.

**Comment by ErwanAliasr1** [comment] 2018-11-27 20:18
I've been able to reproduce. I'll track this issue. That sound like a ceph leak.

**Comment by leseb** [comment] 2018-12-18 15:51
Closed via #100

**Closed as completed by leseb** 2018-12-18 15:51 UTC
